- app/assets/stylesheets/_navbar.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/users/_edit.scss
- app/views/users/_side_bar.html.haml
- app/views/users/edit.html.haml
- db/schema.rb
ユーザー情報を編集できるビューの作成
ユーザーが自身の情報を際に必須のページであるため
> ユーザープロフィール編集ページの作成

- app/assets/stylesheets/_simplefooter.scss
- app/assets/stylesheets/_simpleheader.scss
- app/views/items/new.html.haml
- app/views/layouts/_simplefooter.html.haml
> Simple footer作成

- app/assets/stylesheets/_show.scss
- app/controllers/users_controller.rb
- app/views/users/_side_bar.html.haml
- app/views/users/profile.html.haml
- config/routes.rb
- db/schema.rb
#WHAT
userマイページのプロフィール編集画面
#WHY
プロフィール画面を編集して更新できるようにする
> プロフィール編集画面

- app/assets/stylesheets/_show.scss
- app/views/users/profile.html.haml
> プロフィール修正画面

- app/controllers/items_controller.rb
- db/schema.rb
#What
　商品の詳細ページを作成する。
#Why
　商品の詳細を確認できるようにするため。
> create pull request

- app/assets/javascripts/image.js
- app/assets/stylesheets/item/_show.scss
- app/controllers/items_controller.rb
- app/views/items/show.html.haml
- app/views/layouts/_show-box.html.haml
- spec/controllers/items_controller_spec.rb
#What
　商品の詳細を確認できるページを作る。
　・いいね機能
　・画像のスライド表示
　・SOLDOUT表示　等
#Why
　商品の詳細を確認するため。
> [WIP] 商品詳細ページ

- app/assets/stylesheets/_new-regist.scss
- app/controllers/items_controller.rb
- app/views/addresses/new.html.haml
- app/views/cards/index.html.haml
- app/views/cards/new.html.haml
- app/views/devise/registrations/new.html.haml
- app/views/devise/registrations/sms.html.haml
- app/views/layouts/_progressbar.html.haml
- app/views/users/smsConfirmation.html.haml
#What
ユーザー新規登録のフロント部分を完成させた。
プログレスバー完成
#Why
ユーザー登録画面はメルカリに必須の機能のため。
> ユーザー登録ページのビュー最終調整

- Gemfile
- app/controllers/users/omniauth_callbacks_controller.rb
- app/models/user.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
#What
ユーザーの新規登録、ログイン（メアド、facebook、Googleの3パターン）
単体テストも書く
#Why
メルカリ同様パスワードより安全なsns認証を実装するため
> 【サーバサイド】ユーザー新規登録、ログイン

- app/controllers/items_controller.rb
- app/views/items/index.html.haml
#What
ビューに名前を反映させた。
#Why
トップページは必要だから。
> [WIP]Item表示

- app/assets/stylesheets/_index.scss
- app/views/items/index.html.haml
#What
人気カテゴリの最新アイテム10件を並べた。
#Why
メルカリでもアイテム40件並んでいるため。
> categoryの新着導入

- app/assets/javascripts/new.js
- app/assets/stylesheets/_error_messages.scss
- app/assets/stylesheets/_new.scss
- app/assets/stylesheets/application.scss
- app/controllers/items_controller.rb
- app/views/items/index.html.haml
- app/views/items/new.html.haml
- app/views/layouts/_error_messages.html.haml
> 出品画面　ビュー修正

- app/assets/javascripts/new.js
- app/controllers/items_controller.rb
- app/views/items/edit.html.haml
- app/views/items/pre_edit.html.haml
- app/views/users/profile.html.haml
- app/views/users/show.html.haml
- config/routes.rb
#What
商品の情報を編集して更新する。
#Why
商品の詳細を購入者の希望に合わせて変更できるから。
> 【サーバサイド】商品情報編集

- app/controllers/items_controller.rb
#What
一覧表示で空文字がブランド候補に入っている不具合を修正しました。
#Why
不具合修正。お客様の不便に繋がるため。
> where.not(brand: "")

- app/controllers/categories_controller.rb
- app/views/categories/show.html.haml
- app/views/items/index.html.haml
- config/routes.rb
#What
カテゴリ機能の最低限のルーティング生成。
#Why
パスを飛ばさないと表示できないから。
> 最低限のルーティング作成

- app/assets/javascripts/image.js
- app/assets/stylesheets/item/_show.scss
- app/assets/stylesheets/order/_new.scss
- app/views/favorites/_like.html.haml
- app/views/items/show.html.haml
- app/views/layouts/_show-box.html.haml
- app/views/users/_side_bar.html.haml
- app/views/users/logout.html.haml
- app/views/users/myitem.html.haml
#What
　・いいねマーク見た目の修正
　・画像のスライド速度UP
　・リンクボタンの修正
　などの細かい修正を行う。
#Why
　完成度を高めるため。
> 商品詳細ページ等の修正

- app/assets/stylesheets/_category.scss
- app/assets/stylesheets/_index.scss
- app/assets/stylesheets/application.scss
- app/controllers/categories_controller.rb
- app/models/category.rb
- app/views/categories/index.html.haml
- app/views/categories/show.html.haml
- app/views/layouts/_header.html.haml
- config/breadcrumbs.rb
#What
カテゴリ機能の実装
#Why
ユーザーのニーズにたいして絞り込みをすることで、ユーザーの利便性を高める。
> [WIP]カテゴリ機能show導入

- app/assets/stylesheets/items/_search.scss
- app/views/items/search.html.haml
#what
検索結果が表示された時のビューを整えた。
#why
ユーザーが見る部分なので、見苦しくない程度にする必要があるため
> 検索結果表示画面の実装

- app/views/items/edit.html.haml
#What
画像部分の修正
#Why
保存した画像を読み込むため
> 商品情報編集-4（画像修正）

- app/assets/javascripts/new.js
- app/assets/stylesheets/_mixin.scss
- app/assets/stylesheets/_new.scss
- app/views/items/new.html.haml
#What
画像投稿部分のビューの崩れの修正
#why
見た目を綺麗にするため
> 出品画面およびjsファイルの修正

- app/assets/javascripts/new.js
- app/assets/stylesheets/_new.scss
- app/assets/stylesheets/_registration.scss
- app/views/addresses/new.html.haml
- app/views/items/edit.html.haml
- app/views/items/new.html.haml
#What
商品出品の画面修正（カテゴリー）
都道府県のセレクトバー
#Why
ビューが崩れていて見栄えが悪いため
> 出品　編集のビュー修正

- app/assets/javascripts/category.js
- app/assets/stylesheets/_header.scss
- app/controllers/items_controller.rb
- app/views/layouts/_header.html.haml
#What
カテゴリ機能をjsで非同期通信できるようにした。
#Why
カテゴリ機能はユーザーの利便性をあげる。
> カテゴリ機能ほぼ完成
